### PR TITLE
[RNTuple] fix multi page reading for Index32/Index64 columns

### LINKED ISSUE #312: [RNTuple] Wrong offset `Index32/Index64` array when read from multiple pages
```julia
julia> rnt = LazyTree("./DAOD_TRUTH1.zprime125.rntuple.root", "RNT:CollectionTree", "AntiKt4TruthDressedWZJetsAux:");

julia> for i in 1:20000
           @show i
           rnt.var"AntiKt4TruthDressedWZJetsAux:"[i]
       end
i = 1
Int.(first(jloffset, 3)) = [1, 6, 22]
Int.(last(jloffset, 3)) = [4700, 4706, 4722]
eachindex(content) = Base.OneTo(4721)
Int.(first(jloffset, 3)) = [1, 6, 22]
Int.(last(jloffset, 3)) = [4700, 4706, 4722]
eachindex(content) = Base.OneTo(4721)
Int.(first(jloffset, 3)) = [1, 6, 22]
Int.(last(jloffset, 3)) = [4700, 4706, 4722]
eachindex(content) = Base.OneTo(4721)
Int.(first(jloffset, 3)) = [1, 6, 22]
Int.(last(jloffset, 3)) = [4700, 4706, 4722]
eachindex(content) = Base.OneTo(4721)
Int.(first(jloffset, 3)) = [1, 2, 26]
Int.(last(jloffset, 3)) = [46917, 46923, 46929]
eachindex(content) = Base.OneTo(46928)
Int.(first(jloffset, 3)) = [1, 6, 22]
Int.(last(jloffset, 3)) = [4700, 4706, 4722]
eachindex(content) = Base.OneTo(4721)
Int.(first(jloffset, 3)) = [1, 2, 26]
Int.(last(jloffset, 3)) = [46917, 46923, 46929]
eachindex(content) = Base.OneTo(46928)
Int.(first(jloffset, 3)) = [1, 6, 22]
Int.(last(jloffset, 3)) = [4700, 4706, 4722]
eachindex(content) = Base.OneTo(4721)
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
...
i = 528
i = 529
Int.(first(jloffset, 3)) = [1, 10, 31]
Int.(last(jloffset, 3)) = [12907, 12920, 12931]
eachindex(content) = Base.OneTo(12930)
Int.(first(jloffset, 3)) = [1, 10, 31]
Int.(last(jloffset, 3)) = [12907, 12920, 12931]
eachindex(content) = Base.OneTo(12930)
Int.(first(jloffset, 3)) = [1, 10, 31]
Int.(last(jloffset, 3)) = [12907, 12920, 12931]
eachindex(content) = Base.OneTo(12930)
Int.(first(jloffset, 3)) = [1, 10, 31]
Int.(last(jloffset, 3)) = [12907, 12920, 12931]
eachindex(content) = Base.OneTo(12930)
Int.(first(jloffset, 3)) = [1, 31, 35]
Int.(last(jloffset, 3)) = [209989, 210000, 210009]
eachindex(content) = Base.OneTo(128584)
ERROR: ArgumentError: VectorOfArrays inconsistent: Last elem_ptr inconsistent with data indices
  [1] simple_consistency_checks
    @ ~/.julia/packages/ArraysOfArrays/1GYHm/src/vector_of_arrays.jl:140 [inlined]
```

### PR DESCRIPTION
**Pull request by Moelf**
fix #312

see:
- #312

for detailed investigation

### CODE REVIEW

File: src/streamers.jl [hunk 1]
```diff
@@ -80,17 +80,17 @@ function Streamers(io)
         # notice our `TKey` size is not the same as official TKey, can't use sizeof()
         skipped = position(io) - start
         compressedbytes = read(io, tkey.fNbytes - skipped)
-        cname = String(compression_header.algo)
+        cname = compression_header.algo
 
-        if cname == "ZL"
+        if cname == @SVector UInt8['Z', 'L']
```
Comment (tamasgal) [inline src/streamers.jl:85]: These comparisons look a bit weird but it is what it is ;) If we do such checks at more places in future, we should probably extract that or do some dispatch magic.

**Review by tamasgal — APPROVED** [review]
Looks good to me, so far I can tell ;)

File: src/streamers.jl (hunk 1 above)
Comment (Moelf) [reply src/streamers.jl:85]: true, and we have like 3 different such ifelse right now.

poly-Decompression is hard
